### ISSUE TITLE
페이지 하단 행동강령 클릭 시 페이지 링크 오류

### ISSUE THREAD

**Issue by level120** [cloudbandwagon/cloudbandwagon.github.io#14]
증상
* 페이지 하단 행동강령 클릭
* 링크 오류 발생

**Comment by 9bow** [comment]
i18n을 위해 `_data`에 포함한 collection 내의 liquid tag를 제대로 파싱하지 못하는 이슈로 보입니다.
COC 링크는 장기적으로 사이트 내에 포함되어 고정될 예정이므로, 그 때까지만 임시로 변경하여 사용하려고 합니다;;;

**Comment by level120** [comment]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/10791961/232041244-20034fbe-02c7-4e75-8bfd-1f7278f59c4b.png">

문자가 깨져 뭘로 바꾸는진 모르겠지만 알겠습니다!

**Comment by 9bow** [comment]
PR 상태입니다 ㅎㅎㅎ
요즘 macOS가 한글에 소홀한거 같네요ㅠ
